#!/bin/bash

NAME="text_to_speech_app"
DIR=/home/tts/text-to-speech-app/text_to_audiobook_app
USER=tts
GROUP=tts
WORKERS=3
BIND=unix:/home/tts/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=text_to_audiobook_app.settings
DJANGO_WSGI_MODULE=text_to_audiobook_app.wsgi
LOG_LEVEL=error

cd $DIR

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

/home/tts/.local/bin/poetry run gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-