# Generated by Django 4.0 on 2021-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_textfile_mp3_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='status',
            field=models.CharField(default='Not submitted', max_length=255),
        ),
    ]
