# Generated by Django 4.0 on 2021-12-10 06:24

from django.db import migrations, models
import text.models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_textfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=text.models.Image.image_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('operation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Not submitted', max_length=255)),
            ],
        ),
    ]
