# Generated by Django 4.0 on 2021-12-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='text.textfile'),
        ),
    ]
