# Generated by Django 4.0 on 2021-12-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_image_text_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('text_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='text.textfile')),
            ],
        ),
    ]
