# Generated by Django 4.0 on 2021-12-13 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='text_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_image', to='text.textfile'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='text_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='text.textfile'),
        ),
    ]
