# Generated by Django 4.0 on 2021-12-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_textfile_date_added_alter_image_text_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
